import type { Metadata } from "next";
import { DetailSection } from "@/components/detail-section";
import { EditorialMediaHero } from "@/components/editorial-media-hero";
import Link from "next/link";
import { notFound } from "next/navigation";
import type { BenchmarkDataset } from "@/components/editorial-sections";
// Generated by benchmarks/experiments/export_web.py in the arcadedb-embedded-python
// repo, from the frozen runs_paper.csv. Regenerate and copy rather than editing.
import rawArcadeDbBenchmarks from "@/data/arcadedb-benchmarks.json";

const arcadeDbBenchmarks = rawArcadeDbBenchmarks as unknown as BenchmarkDataset;
import { getProject, getSubprojects, projects } from "@/lib/projects";
import { EditorialProjectPage, buildAcknowledgements } from "../editorial-project-page";
import { SubprojectsSection } from "../subprojects-section";
import styles from "../projects.module.css";

type Params = {
  slug: string;
};

export function generateStaticParams() {
  return projects.map((project) => ({ slug: project.slug }));
}

export async function generateMetadata({ params }: { params: Promise<Params> }): Promise<Metadata> {
  const { slug } = await params;
  const project = getProject(slug);

  if (!project) {
    return { title: "Project" };
  }

  return {
    title: project.title,
    description: project.summary,
    openGraph: project.image
      ? {
          images: [
            {
              url: project.image.src,
              alt: project.image.alt,
            },
          ],
        }
      : undefined,
    twitter: project.image
      ? {
          card: "summary_large_image",
          images: [project.image.src],
        }
      : undefined,
  };
}

export default async function ProjectDetailPage({ params }: { params: Promise<Params> }) {
  const { slug } = await params;

  const project = getProject(slug);

  if (!project) {
    notFound();
  }

  const subprojects = getSubprojects(project);
  const parentProject = projects.find((candidate) => candidate.subprojectSlugs?.includes(project.slug));
  const projectContext = (
    <>
      <Link href="/projects">Projects</Link>
      {parentProject ? (
        <>
          {" / "}
          <Link href={`/projects/${parentProject.slug}`}>{parentProject.title}</Link>
        </>
      ) : null}
    </>
  );
  const acknowledgementsSectionContent = buildAcknowledgements(project);
  const projectLinks = project.links.map((link) => ({
    ...link,
    isInternal: link.href.startsWith("/"),
  }));
  const editorialPage = project.editorialPage ?? project.subprojectPage;
  const editorialSections = editorialPage?.sections ?? [];
  const isEditorialPage = editorialPage?.layout === "editorial" && editorialSections.length > 0;
  if (isEditorialPage) {
    return <EditorialProjectPage project={project} dataset={arcadeDbBenchmarks} />;
  }

  if (project.showOnProjectsIndex) {
    return (
      <main className={styles.detailPage}>
        <EditorialMediaHero
          context={<Link href="/projects">Projects</Link>}
          eyebrow="Project"
          title={project.title}
          intro={project.summary}
          titleVariant="feature"
          imageSrc={project.image?.src}
          imageAlt={project.image?.alt}
          showFallbackMedia={!project.image}
        />

        <DetailSection
          eyebrow="Why it exists"
          title={project.featuredPage?.problemHeading ?? "The project-level problem this work is trying to solve."}
        >
            <p>{project.problem}</p>
        </DetailSection>

        <DetailSection
          eyebrow="What it is building"
          title={project.featuredPage?.solutionHeading ?? "The work is organized as a larger project, not just a list of repositories."}
        >
            <p>{project.solution}</p>
            {project.impact ? <p>{project.impact}</p> : null}
        </DetailSection>

        {subprojects.length > 0 ? (
          <SubprojectsSection
            subprojects={subprojects}
          />
        ) : null}

        {acknowledgementsSectionContent ? (
          <DetailSection
            eyebrow="Acknowledgements"
            title={project.featuredPage?.acknowledgementsHeading ?? "Project support."}
          >
            {acknowledgementsSectionContent}
          </DetailSection>
        ) : null}
      </main>
    );
  }

  return (
    <main className={styles.subprojectPage}>
      <EditorialMediaHero
        context={projectContext}
        eyebrow="Subproject"
        title={project.title}
        intro={project.summary}
        titleVariant="feature"
        imageSrc={project.image?.src}
        imageAlt={project.image?.alt}
        showFallbackMedia={!project.image}
      />

      <DetailSection eyebrow="Why it exists" title={project.subprojectPage?.problemHeading ?? "The problem"}>
          <p>{project.problem}</p>
      </DetailSection>

      <DetailSection eyebrow="What it is building" title={project.subprojectPage?.solutionHeading ?? "What we are building"}>
          <p>{project.solution}</p>
      </DetailSection>

      {project.impact ? (
        <DetailSection eyebrow="Why it matters" title={project.subprojectPage?.impactHeading ?? "Why it matters"}>
            <p>{project.impact}</p>
        </DetailSection>
      ) : null}

      {project.subprojectPage?.highlights?.length ? (
        <DetailSection
          eyebrow="Highlights"
          title={project.subprojectPage.highlightsHeading ?? "Highlights."}
          bodyVariant="plain"
          bodyClassName={styles.subprojectHighlightList}
        >
            {project.subprojectPage.highlights.map((highlight) => (
              <article className={styles.subprojectHighlightItem} key={highlight.title}>
                <h3>{highlight.title}</h3>
                <p>{highlight.description}</p>
              </article>
            ))}
        </DetailSection>
      ) : null}

      {projectLinks.length > 0 ? (
        <DetailSection
          eyebrow="Links"
          title={project.subprojectPage?.linksHeading ?? "Links."}
          bodyVariant="plain"
          bodyClassName={styles.subprojectLinksList}
        >
            {projectLinks.map((link) =>
              link.isInternal ? (
                <Link className={styles.subprojectLinkRow} href={link.href} key={link.href}>
                  <span>{link.label}</span>
                  <span className={styles.subprojectLinkAction}>Open</span>
                </Link>
              ) : (
                <a
                  className={styles.subprojectLinkRow}
                  href={link.href}
                  key={link.href}
                  target="_blank"
                  rel="noopener noreferrer"
                >
                  <span>{link.label}</span>
                  <span className={styles.subprojectLinkAction}>Open</span>
                </a>
              ),
            )}
        </DetailSection>
      ) : null}

      {subprojects.length > 0 ? (
        <DetailSection
          eyebrow="Project structure"
          title="Subprojects."
          bodyVariant="plain"
          bodyClassName={styles.subprojectLinksList}
        >
            {subprojects.map((subproject) => (
              <Link className={styles.subprojectLinkRow} href={`/projects/${subproject.slug}`} key={subproject.slug}>
                <span>
                  <strong>{subproject.title}</strong>
                  <small className={styles.subprojectLinkSummary}>{subproject.summary}</small>
                </span>
                <span className={styles.subprojectLinkAction}>Open</span>
              </Link>
            ))}
        </DetailSection>
      ) : null}

      {acknowledgementsSectionContent ? (
        <DetailSection eyebrow="Acknowledgements" title="Project support.">
          {acknowledgementsSectionContent}
        </DetailSection>
      ) : null}
    </main>
  );
}