# site settings
title: HumemAI
subtitle: A Machine With Human-Like Memory Systems
email: info@humem.ai
# description: Empower yourself with HumemAI.<br /> open-sourced for everyone.
description: Currently under construction. <br />Check out https://taewoon.kim/projects/human-memory/
baseurl: "/forty-jekyll-theme" # the subpath of your site, e.g. /blog
url: https://humem.ai # the base hostname & protocol for your site
author: Taewoon Kim
street_address: Road to AGI
city: Amsterdam
state: North Holland
# zip_code: 42
country: The Netherlands
# phone: (716) 555-5555

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  envelope: mailto:info@humem.ai
  GitHub: https://github.com/humemai
  GitLab:
  # Google-Plus: https://plus.google.com/u/0/+AndrewBanchich
  Instagram:
  LinkedIn: https://www.linkedin.com/in/tae898
  Twitter: https://twitter.com/tae898
  Facebook:
  Slack:

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
